# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "beta"
    directory: "/"
    schedule:
      interval: "daily"
